services:
  postgres:
  image: postgres
  container_name: postgres
  restart: always
  ports:
    - 5433:5432
  env_file:
    - ./back-end/.env.test
  volumes:
    - postgres-data:/var/lib/postgresql/data

api:
  container_name: api
  build: ./back-end
  ports: 
    - 5000:5000
  env_file:
    - ./back-end/.env.test
  depends-on:
    - postgres
  
volumes:
 postres-data: